dist: trusty

cache:
  directories:
  - $HOME/.gradle/caches

language: java

matrix:
  include:
    - jdk: oraclejdk8
      env: IDEA_VERSION="2016.1"
    - jdk: oraclejdk8
      env: IDEA_VERSION="2016.2"
    - jdk: oraclejdk8
      env: IDEA_VERSION="2016.3"
    - jdk: oraclejdk8
      env: IDEA_VERSION="2017.1"
    - jdk: oraclejdk8
      env: IDEA_VERSION="2017.2"
    - jdk: oraclejdk8
      env: IDEA_VERSION="2017.3"
    - jdk: oraclejdk8
      env: IDEA_VERSION="2018.1"
    - jdk: oraclejdk8
      env: IDEA_VERSION="2018.2"
    - jdk: oraclejdk8
      env: IDEA_VERSION="2018.3"
#    - jdk: oraclejdk8
#      env: IDEA_VERSION="LATEST-EAP-SNAPSHOT"

install: ./gradlew -P ideaVersion=$IDEA_VERSION assemble

script: ./gradlew -P ideaVersion=$IDEA_VERSION build

